services:

# this yaml uses an ubuntu 16.04 imges with maven/java/tomcat preinstalled 
# (check dependencies install part of the Dockerfile)
image: ubuntu_dexms:1.0

stages:
  - install
  - build
  - test
  - deploy
  - start

job_install_ci:
  stage: install
  tags:
    - test
  script:
    - pwd
    - ls

job_build_ci:
  stage: build
  tags:
    - test
  script:
    - source /etc/environment && mvn clean verify
    - source /etc/environment && mvn install
  artifacts:
    paths:
    - dexms-service/target/

job_test_ci:
  stage: test
  tags:
    - test
  script:
    - source /etc/environment && mvn test
    - cp dexms-service/target/dexms-service-1.0.0-SNAPSHOT.war /usr/local/apache-tomcat-8.5.42/webapps/
    - /usr/local/apache-tomcat-8.5.42/bin/startup.sh
    - sleep 10
    - wget http://localhost:8080/dexms-service-1.0.0-SNAPSHOT/
  artifacts:
    paths:
    - dexms-service/target/
    
    

